# Tasks for wlsprep role.

# ==> Configure Linux

- name: Update 
  yum: name="*" state=latest

- name: Install required libraries
  yum: name="{{ item }}" state=latest
  with_items: "{{ package_list }}"

- name: copy and install libstdc++.33 the hardway
  copy: src=lib/compat-libstdc++-33-3.2.3-72.el7.x86_64.rpm dest=/tmp/compat-libstdc++-33-3.2.3-72.el7.x86_64.rpm
- yum: name=/tmp/compat-libstdc++-33-3.2.3-72.el7.x86_64.rpm state=present

- name: Check SELinux status
  shell: selinuxenabled && echo enabled || echo disabled
  register: selinux_status

- name: Disable SELinux
  selinux: state=disabled
  when: selinux_status.stdout != 'disabled'

- name: Disable firewalld (firewalld)
  service: name=firewalld state=stopped enabled=no
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7") or
        (ansible_distribution == "RedHat" and ansible_distribution_major_version == "7")

- name: Disable iptables (iptables)
  service: name=iptables state=stopped enabled=no
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6") or
        (ansible_distribution == "RedHat" and ansible_distribution_major_version == "6")

- name: Change kernel parameters
  sysctl: name="{{ item.key }}" value="{{ item.value }}" state=present
  with_dict: "{{ kernel_params }}"

- name: Create groups
  group: name="{{ item }}" state=present
  with_items:
    - "{{ oracle_group }}"
    - "oper"
    - "dba"

- name: Create user
  user: name={{ oracle_user }} group={{ oracle_group }} groups=oper,dba state=present

- name: set PAM limits
  pam_limits:
    domain:     "{{ item.domain }}"
    value:      "{{ item.value }}"
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
  with_items:
    - { domain: '*',      limit_type: 'soft', limit_item: 'nofile',  value: 2048 }
    - { domain: '*',      limit_type: 'hard', limit_item: 'nofile',  value: 8192 }
    - { domain: 'oracle', limit_type: 'soft', limit_item: 'nofile',  value: 65536 }
    - { domain: 'oracle', limit_type: 'hard', limit_item: 'nofile',  value: 65536 }
    - { domain: 'oracle', limit_type: 'soft', limit_item: 'nproc',   value: 2048 }
    - { domain: 'oracle', limit_type: 'hard', limit_item: 'nproc',   value: 16384 }
    - { domain: 'oracle', limit_type: 'soft', limit_item: 'memlock', value: 1048576 }
    - { domain: 'oracle', limit_type: 'hard', limit_item: 'memlock', value: 1048576 }
    - { domain: 'oracle', limit_type: 'soft', limit_item: 'stack',   value: 10240 }
    
- name: Create a shell profile with file and process limits for oracle user
  template: src=limits.sh.j2 dest=/etc/profile.d/limits.sh owner=root mode=0644
