# Tasks for wlsprep role.

# ==> Configure Linux
- name: Install required libraries
  yum: name={{ item }} state=present
  with_items: packages_list

- name: Disable SELinux
  selinux: state=disabled

- name: Disable firewalld (firewalld)
  service: name=firewalld state=stopped enabled=no

- name: Disable iptables (iptables)
  service: name=iptables state=stopped enabled=no

- name: Change kernel parameters
  sysctl: name="{{ item.key }}" value="{{ item.value }}" state=present
  with_dict: kernel_params

# ==> Create user and groups
- name: Create groups
  group: name={{ oracle_group_name }} state=present

- name: Create user
  user: name={{ oracle_user_name }} groups={{ oracle_group_name }}
#  user: name={{ oracle_user_name }} groups={{ oracle_group_name }} password={{ oracle_user_password }}

# ==> Add open file and process limits for oracle user
- name: Add soft limit number of open files
  lineinfile: dest=/etc/security/limits.conf line='{{ oracle_user_name }} soft  nofile  {{ soft_no_file }}'

- name: Add hard limit for number of open files
  lineinfile: dest=/etc/security/limits.conf line='{{ oracle_user_name }} hard  nofile  {{ hard_no_file }}'

- name: Add soft limit for number of processes
  lineinfile: dest=/etc/security/limits.conf line='{{ oracle_user_name }} soft  nproc   {{ soft_nproc }}'

- name: Add hard limit for number of processes
  lineinfile: dest=/etc/security/limits.conf line='{{ oracle_user_name }} hard  nproc   {{ hard_nproc }}'

- name: Create a shell profile with file and process limits for oracle user
  template: src=limits.sh.j2 dest=/etc/profile.d/
